version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'financial'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './mysql/data/:/var/lib/mysql'
    ports:
      - 3306:3306
