service: financeiro

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { 'Fn::GetAtt': ['StockDynamoDBTable', 'Arn'] }
  environment:

package:
  exclude:
    - node_modules/**/*
  include: handler.ts

functions:
  graphql:
    handler: src/handler.server
    timeout: 1000
    events:
      - http:
          path: /api
          method: ANY
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  tableName: 'stock'
  dynamodb:
    start:
      migrate: true

resources:
  Resources:
    StockDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: stock
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
